local profile=T{}
profile.jobs=T{}
profile.sequences=T{}

profile.jobs.BRD=T{ 'SongOne', 'SongTwo', 'SongThree', 'CarolElement', 'ThrenodyElement' }
profile.jobs.BST=T{ 'Accuracy', 'BstIdleMain', 'BstIdleSub', 'BstBlJug', 'BstCllBstJug', 'BstStrategy', 'WeaponStrategy', 'BstWS' }
profile.jobs.BLM=T{ 'EleElement', 'BlmWS' }
profile.jobs.BLU=T{ 'Accuracy', 'BlueStrategy', 'BluWS' }
profile.jobs.COR=T{ 'Accuracy', 'CorStrategy', 'RollOne', 'RollTwo', 'CorWS' }
profile.jobs.DNC=T{}
profile.jobs.DRK=T{}
profile.jobs.DRG=T{}
profile.jobs.GEO=T{ 'Accuracy', 'EleElement', 'Bubble', 'Luopan', 'Entrust', 'GeoWS' }
profile.jobs.MNK=T{}
profile.jobs.NIN=T{ 'NinIdleMain', 'NinStrategy' }
profile.jobs.PLD=T{ 'PldIdleSub' }
profile.jobs.PUP=T{ 'Accuracy', 'PuppetStrategy', 'ManeuverOne', 'ManeuverTwo', 'ManeuverThree', 'PupWS' }
profile.jobs.RNG=T{}
profile.jobs.RDM=T{}
profile.jobs.RUN=T{}
profile.jobs.SAM=T{ 'Accuracy', 'SamWS' }
profile.jobs.SCH=T{ 'Accuracy', 'EleElement', 'SchSkillchain', 'SchWS' }
profile.jobs.SMN=T{}
profile.jobs.THF=T{}
profile.jobs.WAR=T{}
profile.jobs.WHM=T{ 'Boost', 'BarElement', 'BarStatus', 'WhmWS' }

profile.sequences.Accuracy=T{}
profile.sequences.Accuracy.Name='Accuracy'
profile.sequences.Accuracy.Values=T{ 'Low', 'High' }
profile.sequences.Accuracy.Default='Low'
profile.sequences.Accuracy.Low='ac_var_Accuracy_Low'
profile.sequences.Accuracy.High='ac_var_Accuracy_High'

profile.sequences.BarElement=T{}
profile.sequences.BarElement.Name= 'Bar Element'
profile.sequences.BarElement.Values=T{ 'Fire', 'Stone', 'Water', 'Wind', 'Ice', 'Thunder' }
profile.sequences.BarElement.Default='Fire'
profile.sequences.BarElement.Fire='jh_whm_setbarelement_fire'
profile.sequences.BarElement.Stone='jh_whm_setbarelement_stone'
profile.sequences.BarElement.Water='jh_whm_setbarelement_water'
profile.sequences.BarElement.Wind='jh_whm_setbarelement_wind'
profile.sequences.BarElement.Ice='jh_whm_setbarelement_ice'
profile.sequences.BarElement.Thunder='jh_whm_setbarelement_thunder'

profile.sequences.BarStatus=T{}
profile.sequences.BarStatus.Name='Bar Status'
profile.sequences.BarStatus.Values=T{ 'Amnesia', 'Blind', 'Para', 'Petra', 'Vira', 'Poison', 'Silence', 'Sleep' } 
profile.sequences.BarStatus.Default='Amnesia'
profile.sequences.BarStatus.Amnesia='jh_whm_setbarstatus_amnesia'
profile.sequences.BarStatus.Blind='jh_whm_setbarstatus_blind'
profile.sequences.BarStatus.Para='jh_whm_setbarstatus_paralysis'
profile.sequences.BarStatus.Petra='jh_whm_setbarstatus_petrification'
profile.sequences.BarStatus.Vira='jh_whm_setbarstatus_plague'
profile.sequences.BarStatus.Poison='jh_whm_setbarstatus_poison'
profile.sequences.BarStatus.Silence='jh_whm_setbarstatus_silence'
profile.sequences.BarStatus.Sleep='jh_whm_setbarstatus_sleep'

profile.sequences.Boost=T{}
profile.sequences.Boost.Name= Boost
profile.sequences.Boost.Values=T{ 'STR', 'INT', 'VIT', 'DEX', 'AGI', 'CHR' }
profile.sequences.Boost.Default='STR'
profile.sequences.Boost.STR='jh_setboost_str'
profile.sequences.Boost.INT='jh_setboost_int'
profile.sequences.Boost.VIT='jh_setboost_vit'
profile.sequences.Boost.DEX='jh_setboost_dex'
profile.sequences.Boost.AGI='jh_setboost_agi'
profile.sequences.Boost.CHR='jh_setboost_chr'

profile.sequences.BlmWS=T{}
profile.sequences.BlmWS.Name='BLM WS'
profile.sequences.BlmWS.Values=T{ 'Shattersoul', 'Myrkr', 'Cataclysm' }
profile.sequences.BlmWS.Default='Shattersoul'
profile.sequences.BlmWS.Shattersoul='ws_setting_shattersoul'
profile.sequences.BlmWS.Myrkr='ws_setting_myrkr'
profile.sequences.BlmWS.Cataclysm='ws_setting_cataclysm'

profile.sequences.BluStrategy=T{}
profile.sequences.BluStrategy.Name='Strategy'
profile.sequences.BluStrategy.Values=T{ 'MstrMelee', 'MstrDT', 'Refresh' }
profile.sequences.BluStrategy.Default='MstrMelee'
profile.sequences.BluStrategy.MstrMelee='ac_var_Strategy_MstrMelee'
profile.sequences.BluStrategy.MstrDT='ac_var_Strategy_MstrDT'
profile.sequences.BluStrategy.TH='ac_var_Strategy_TH'
profile.sequences.BluStrategy.Refresh='ac_var_Strategy_Refresh'

profile.sequences.BstIdleMain=T{}
profile.sequences.BstIdleMain.Name='Main'
profile.sequences.BstIdleMain.Values=T{ 'NoSwap', 'Aymur', 'PetDT', 'Arktoi' }
profile.sequences.BstIdleMain.Default='NoSwap'
profile.sequences.BstIdleMain.NoSwap='ac_var_IdleMain_NoSwap'
profile.sequences.BstIdleMain.Aymur='ac_var_IdleMain_Aymur'
profile.sequences.BstIdleMain.PetDT='ac_var_IdleMain_PetDT'
profile.sequences.BstIdleMain.Arktoi='ac_var_IdleMain_Arktoi'

profile.sequences.BstIdleSub=T{}
profile.sequences.BstIdleSub.Name='Sub'
profile.sequences.BstIdleSub.Values=T{ 'Arktoi', 'PetPdt', 'PetDt', 'Beatific', 'Adapa' }
profile.sequences.BstIdleSub.Default='Beatific'
profile.sequences.BstIdleSub.Arktoi='ac_var_IdleSub_Arktoi'
profile.sequences.BstIdleSub.PetPdt='ac_var_IdleSub_PetPdt'
profile.sequences.BstIdleSub.PetDt='ac_var_IdleSub_PetDt'
profile.sequences.BstIdleSub.Beatific='ac_var_IdleSub_Beatific'
profile.sequences.BstIdleSub.Adapa='ac_var_IdleSub_Adapa'

profile.sequences.BstBlJug=T{}
profile.sequences.BstBlJug.Name='BL Jug'
profile.sequences.BstBlJug.Values=T{ 'Lizard', 'Tiger', 'Cricket', 'Bird', 'Snapweed', 'Fly', 'Piggy', 'Mandy', 'Fish', 'Raptor' }
profile.sequences.BstBlJug.Default='Lizard'
profile.sequences.BstBlJug.Lizard= 'ac_var_BlJug_Lizard'
profile.sequences.BstBlJug.Tiger= 'ac_var_BlJug_Tiger'
profile.sequences.BstBlJug.Cricket= 'ac_var_BlJug_Cricket'
profile.sequences.BstBlJug.Bird= 'ac_var_BlJug_Bird'
profile.sequences.BstBlJug.Snapweed= 'ac_var_BlJug_Snapweed'
profile.sequences.BstBlJug.Fly= 'ac_var_BlJug_Fly'
profile.sequences.BstBlJug.Piggy= 'ac_var_BlJug_Piggy'
profile.sequences.BstBlJug.Mandy= 'ac_var_BlJug_Mandy'
profile.sequences.BstBlJug.Fish= 'ac_var_BlJug_Fish'
profile.sequences.BstBlJug.Raptor= 'ac_var_BlJug_Raptor'

profile.sequences.BstCllBstJug=T{}
profile.sequences.BstCllBstJug.Name='Call Beast Jug'
profile.sequences.BstCllBstJug.Values=T{ 'Lizard', 'Tiger', 'Cricket', 'Bird', 'Snapweed', 'Fly', 'Piggy', 'Fish', 'Raptor' }
profile.sequences.BstCllBstJug.Default='Lizard'
profile.sequences.BstCllBstJug.Lizard= 'ac_var_CllBstJug_Lizard'
profile.sequences.BstCllBstJug.Tiger= 'ac_var_CllBstJug_Tiger'
profile.sequences.BstCllBstJug.Cricket= 'ac_var_CllBstJug_Cricket'
profile.sequences.BstCllBstJug.Bird= 'ac_var_CllBstJug_Bird'
profile.sequences.BstCllBstJug.Snapweed= 'ac_var_CllBstJug_Snapweed'
profile.sequences.BstCllBstJug.Fly= 'ac_var_CllBstJug_Fly'
profile.sequences.BstCllBstJug.Piggy= 'ac_var_CllBstJug_Piggy'
profile.sequences.BstCllBstJug.Mandy= 'ac_var_CllBstJug_Mandy'
profile.sequences.BstCllBstJug.Fish= 'ac_var_CllBstJug_Fish'
profile.sequences.BstCllBstJug.Raptor= 'ac_var_CllBstJug_Raptor'

profile.sequences.BstStrategy=T{}
profile.sequences.BstStrategy.Name='Pet Strategy'
profile.sequences.BstStrategy.Values=T{ 'MstrMelee', 'PetOnly', '119PetOnly', 'MasterDT' }
profile.sequences.BstStrategy.Default='MstrMelee'
profile.sequences.BstStrategy.MstrMelee='ac_var_Strategy_MstMelee'
profile.sequences.BstStrategy.PetOnly='ac_var_Strategy_PetOnly'
profile.sequences.BstStrategy['119PetOnly']='ac_var_Strategy_119PetOnly'
profile.sequences.BstStrategy.MasterDT='ac_var_Strategy_MasterDT'

profile.sequences.BstWS=T{}
profile.sequences.BstWS.Name='Weaponskill'
profile.sequences.BstWS.Values=T{ 'Primal_Rend', 'Cloud_Splitter', 'Mistral_Axe', 'Decimation', 'Ruinator' }
profile.sequences.BstWS.Default='Primal_Rend'
profile.sequences.BstWS.Primal_Rend='ws_setting_primal_rend'
profile.sequences.BstWS.Cloud_Splitter='ws_setting_cloud_splitter'
profile.sequences.BstWS.Mistral_Axe='ws_setting_mistral_axe'
profile.sequences.BstWS.Decimation='ws_setting_decimation'
profile.sequences.BstWS.Ruinator='ws_setting_ruinator'

profile.sequences.Bubble=T{}
profile.sequences.Bubble.Name='Bubble'
profile.sequences.Bubble.Values=T{ 'Regen', 'Refresh', 'Haste', 'StrUp', 'DexUp', 'VitUp', 'AgiUp', 'IntUp', 'MndUp', 'ChrUp', 'PtAttUp', 'PtDefUp', 'PtMagAttUp', 'PtMagDefUp', 'PtAccUp', 'PtEvaUp', 'PtMagAccUp', 'PtMagEvaUp', 'EnAttDwn', 'EnDefDwn', 'EnMagAttDwn', 'EnMagDefDwn', 'EnAccDwn', 'EnEvaDwn', 'EnMagAccDwn', 'EnMagEvaDwn' }
profile.sequences.Bubble.Default='Refresh'
profile.sequences.Bubble.Regen='bubble_regen'
profile.sequences.Bubble.Refresh='bubble_refresh'
profile.sequences.Bubble.Haste='bubble_haste'
profile.sequences.Bubble.StrUp='bubble_str'
profile.sequences.Bubble.DexUp='bubble_dex'
profile.sequences.Bubble.VitUp='bubble_vit'
profile.sequences.Bubble.AgiUp='bubble_agi'
profile.sequences.Bubble.IntUp='bubble_int'
profile.sequences.Bubble.MndUp='bubble_mnd'
profile.sequences.Bubble.ChrUp='bubble_chr'
profile.sequences.Bubble.PtAttUp='bubble_fury'
profile.sequences.Bubble.PtDefUp='bubble_def'
profile.sequences.Bubble.PtMagAttUp='bubble_acumen'
profile.sequences.Bubble.PtMagDefUp='bubble_fend'
profile.sequences.Bubble.PtAccUp='bubble_precision'
profile.sequences.Bubble.PtEvaUp='bubble_voidance'
profile.sequences.Bubble.PtMagAccUp='bubble_focus'
profile.sequences.Bubble.PtMagEvaUp='bubble_attunement'
profile.sequences.Bubble.EnAttDwn='bubble_wilt'
profile.sequences.Bubble.EnDefDwn='bubble_frailty'
profile.sequences.Bubble.EnMagAttDwn='bubble_fade'
profile.sequences.Bubble.EnMagDefDwn='bubble_malaise'
profile.sequences.Bubble.EnAccDwn='bubble_slip'
profile.sequences.Bubble.EnEvaDwn='bubble_torpor'
profile.sequences.Bubble.EnMagAccDwn='bubble_vex'
profile.sequences.Bubble.EnMagEvaDwn='bubble_langour'

profile.sequences.CarolElement=T{}
profile.sequences.CarolElement.Name='Carol Element'
profile.sequences.CarolElement.Values=T{ 'Fire', 'Stone', 'Water', 'Wind', 'Ice', 'Thunder', 'Light', 'Dark' }
profile.sequences.CarolElement.Default='Fire'
profile.sequences.CarolElement.Fire='brd_carol_element_fire'
profile.sequences.CarolElement.Stone='brd_carol_element_stone'
profile.sequences.CarolElement.Water='brd_carol_element_water'
profile.sequences.CarolElement.Wind='brd_carol_element_wind'
profile.sequences.CarolElement.Ice='brd_carol_element_ice'
profile.sequences.CarolElement.Thunder='brd_carol_element_thunder'
profile.sequences.CarolElement.Light='brd_carol_element_light'
profile.sequences.CarolElement.Dark='brd_carol_element_dark'

profile.sequences.CorStrategy=T{}
profile.sequences.CorStrategy.Name='Strategy'
profile.sequences.CorStrategy.Values=T{ 'MstrMelee', 'MstrDT', 'TH', 'Refresh' }
profile.sequences.CorStrategy.Default='MstrMelee'
profile.sequences.CorStrategy.MstrMelee='ac_var_Strategy_MstrMelee'
profile.sequences.CorStrategy.MstrDT='ac_var_Strategy_MstrDT'
profile.sequences.CorStrategy.TH='ac_var_Strategy_TH'
profile.sequences.CorStrategy.Refresh='ac_var_Strategy_Refresh'

profile.sequences.CorWS=T{}
profile.sequences.CorWS.Name='WS'
profile.sequences.CorWS.Values=T{ 'Savage_Blade', 'Requiescat', 'Evisceration', 'Leaden_Salute', 'Wildfire', 'Last_Stand' }
profile.sequences.CorWS.Default='Savage_Blade'
profile.sequences.CorWS.Savage_Blade='savageblade'
profile.sequences.CorWS.Requiescat='requiescat'
profile.sequences.CorWS.Evisceration='evisceration'
profile.sequences.CorWS.Leaden_Salute='leadensalute'
profile.sequences.CorWS.Wildfire='wildfire'
profile.sequences.CorWS.Last_Stand='laststand'

profile.sequences.EleElement=T{}
profile.sequences.EleElement.Name='Elemental Element'
profile.sequences.EleElement.Values=T{ 'Fire', 'Stone', 'Water', 'Wind', 'Ice', 'Thunder', 'Light', 'Dark' }
profile.sequences.EleElement.Default='Fire'
profile.sequences.EleElement.Fire='nuke_element_fire'
profile.sequences.EleElement.Stone='nuke_element_stone'
profile.sequences.EleElement.Water='nuke_element_water'
profile.sequences.EleElement.Wind='nuke_element_wind'
profile.sequences.EleElement.Ice='nuke_element_ice'
profile.sequences.EleElement.Thunder='nuke_element_thunder'
profile.sequences.EleElement.Light='nuke_element_light'
profile.sequences.EleElement.Dark='nuke_element_dark'

profile.sequences.Entrust=T{}
profile.sequences.Entrust.Name='Entrust'
profile.sequences.Entrust.Values=T{ 'Regen', 'Refresh', 'Haste', 'StrUp', 'DexUp', 'VitUp', 'AgiUp', 'IntUp', 'MndUp', 'ChrUp', 'PtAttUp', 'PtDefUp', 'PtMagAttUp', 'PtMagDefUp', 'PtAccUp', 'PtEvaUp', 'PtMagAccUp', 'PtMagEvaUp', 'EnAttDwn', 'EnDefDwn', 'EnMagAttDwn', 'EnMagDefDwn', 'EnAccDwn', 'EnEvaDwn', 'EnMagAccDwn', 'EnMagEvaDwn' }
profile.sequences.Entrust.Default='Refresh'
profile.sequences.Entrust.Regen='entrust_regen'
profile.sequences.Entrust.Refresh='entrust_refresh'
profile.sequences.Entrust.Haste='entrust_haste'
profile.sequences.Entrust.StrUp='entrust_str'
profile.sequences.Entrust.DexUp='entrust_dex'
profile.sequences.Entrust.VitUp='entrust_vit'
profile.sequences.Entrust.AgiUp='entrust_agi'
profile.sequences.Entrust.IntUp='entrust_int'
profile.sequences.Entrust.MndUp='entrust_mnd'
profile.sequences.Entrust.ChrUp='entrust_chr'
profile.sequences.Entrust.PtAttUp='entrust_fury'
profile.sequences.Entrust.PtDefUp='entrust_def'
profile.sequences.Entrust.PtMagAttUp='entrust_acumen'
profile.sequences.Entrust.PtMagDefUp='entrust_fend'
profile.sequences.Entrust.PtAccUp='entrust_precision'
profile.sequences.Entrust.PtEvaUp='entrust_voidance'
profile.sequences.Entrust.PtMagAccUp='entrust_focus'
profile.sequences.Entrust.PtMagEvaUp='entrust_attunement'
profile.sequences.Entrust.EnAttDwn='entrust_wilt'
profile.sequences.Entrust.EnDefDwn='entrust_frailty'
profile.sequences.Entrust.EnMagAttDwn='entrust_fade'
profile.sequences.Entrust.EnMagDefDwn='entrust_malaise'
profile.sequences.Entrust.EnAccDwn='entrust_slip'
profile.sequences.Entrust.EnEvaDwn='entrust_torpor'
profile.sequences.Entrust.EnMagAccDwn='entrust_vex'
profile.sequences.Entrust.EnMagEvaDwn='entrust_langour'

profile.sequences.Luopan=T{}
profile.sequences.Luopan.Name='Luopan'
profile.sequences.Luopan.Values=T{ 'Regen', 'Refresh', 'Haste', 'StrUp', 'DexUp', 'VitUp', 'AgiUp', 'IntUp', 'MndUp', 'ChrUp', 'PtAttUp', 'PtDefUp', 'PtMagAttUp', 'PtMagDefUp', 'PtAccUp', 'PtEvaUp', 'PtMagAccUp', 'PtMagEvaUp', 'EnAttDwn', 'EnDefDwn', 'EnMagAttDwn', 'EnMagDefDwn', 'EnAccDwn', 'EnEvaDwn', 'EnMagAccDwn', 'EnMagEvaDwn' }
profile.sequences.Luopan.Default='Refresh'
profile.sequences.Luopan.Regen='luopan_regen'
profile.sequences.Luopan.Refresh='luopan_refresh'
profile.sequences.Luopan.Haste='luopan_haste'
profile.sequences.Luopan.StrUp='luopan_str'
profile.sequences.Luopan.DexUp='luopan_dex'
profile.sequences.Luopan.VitUp='luopan_vit'
profile.sequences.Luopan.AgiUp='luopan_agi'
profile.sequences.Luopan.IntUp='luopan_int'
profile.sequences.Luopan.MndUp='luopan_mnd'
profile.sequences.Luopan.ChrUp='luopan_chr'
profile.sequences.Luopan.PtAttUp='luopan_fury'
profile.sequences.Luopan.PtDefUp='luopan_def'
profile.sequences.Luopan.PtMagAttUp='luopan_acumen'
profile.sequences.Luopan.PtMagDefUp='luopan_fend'
profile.sequences.Luopan.PtAccUp='luopan_precision'
profile.sequences.Luopan.PtEvaUp='luopan_voidance'
profile.sequences.Luopan.PtMagAccUp='luopan_focus'
profile.sequences.Luopan.PtMagEvaUp='luopan_attunement'
profile.sequences.Luopan.EnAttDwn='luopan_wilt'
profile.sequences.Luopan.EnDefDwn='luopan_frailty'
profile.sequences.Luopan.EnMagAttDwn='luopan_fade'
profile.sequences.Luopan.EnMagDefDwn='luopan_malaise'
profile.sequences.Luopan.EnAccDwn='luopan_slip'
profile.sequences.Luopan.EnEvaDwn='luopan_torpor'
profile.sequences.Luopan.EnMagAccDwn='luopan_vex'
profile.sequences.Luopan.EnMagEvaDwn='luopan_langour'

profile.sequences.ManeuverOne=T{}
profile.sequences.ManeuverOne.Name='Mnvr 1'
profile.sequences.ManeuverOne.Values=T{ 'Fire', 'Ice', 'Wind', 'Earth', 'Thunder', 'Water', 'Light', 'Dark' }
profile.sequences.ManeuverOne.Default='Light'
profile.sequences.ManeuverOne.Parameters=T{ 1}
profile.sequences.ManeuverOne.Fire='firem'
profile.sequences.ManeuverOne.Ice='icem'
profile.sequences.ManeuverOne.Wind='windm'
profile.sequences.ManeuverOne.Earth='earthm'
profile.sequences.ManeuverOne.Thunder='thunderm'
profile.sequences.ManeuverOne.Water='waterm'
profile.sequences.ManeuverOne.Light='lightm'
profile.sequences.ManeuverOne.Dark='darkm'

profile.sequences.ManeuverTwo=T{}
profile.sequences.ManeuverTwo.Name='Mnvr 2'
profile.sequences.ManeuverTwo.Values=T{ 'Fire', 'Ice', 'Wind', 'Earth', 'Thunder', 'Water', 'Light', 'Dark' }
profile.sequences.ManeuverTwo.Default='Fire'
profile.sequences.ManeuverTwo.Parameters=T{ 2}
profile.sequences.ManeuverTwo.Fire='firem'
profile.sequences.ManeuverTwo.Ice='icem'
profile.sequences.ManeuverTwo.Wind='windm'
profile.sequences.ManeuverTwo.Earth='earthm'
profile.sequences.ManeuverTwo.Thunder='thunderm'
profile.sequences.ManeuverTwo.Water='waterm'
profile.sequences.ManeuverTwo.Light='lightm'
profile.sequences.ManeuverTwo.Dark='darkm'

profile.sequences.ManeuverThree=T{}
profile.sequences.ManeuverThree.Name='Mnvr 3'
profile.sequences.ManeuverThree.Values=T{ 'Fire', 'Ice', 'Wind', 'Earth', 'Thunder', 'Water', 'Light', 'Dark' }
profile.sequences.ManeuverThree.Default='Wind'
profile.sequences.ManeuverThree.Parameters=T{ 3}
profile.sequences.ManeuverThree.Fire='firem'
profile.sequences.ManeuverThree.Ice='icem'
profile.sequences.ManeuverThree.Wind='windm'
profile.sequences.ManeuverThree.Earth='earthm'
profile.sequences.ManeuverThree.Thunder='thunderm'
profile.sequences.ManeuverThree.Water='waterm'
profile.sequences.ManeuverThree.Light='lightm'
profile.sequences.ManeuverThree.Dark='darkm'

profile.sequences.PuppetStrategy=T{}
profile.sequences.PuppetStrategy.Name='Pet Strategy'
profile.sequences.PuppetStrategy.Values=T{ 'MstrMelee', 'PetOnly', '119PetOnly', 'PetMelee', 'MasterDT', 'Overdrive' }
profile.sequences.PuppetStrategy.Default='MstrMelee'
profile.sequences.PuppetStrategy.MstrMelee='ac_var_Strategy_MstrMelee'
profile.sequences.PuppetStrategy.PetOnly='ac_var_Strategy_PetOnly'
profile.sequences.PuppetStrategy.PetMelee='ac_var_Strategy_PetMelee'
profile.sequences.PuppetStrategy['119PetOnly']='ac_var_Strategy_119PetOnly'
profile.sequences.PuppetStrategy.MasterDT='ac_var_Strategy_MasterDT'
profile.sequences.PuppetStrategy.Overdrive='ac_var_Strategy_Overdrive'

profile.sequences.NinIdleMain=T{}
profile.sequences.NinIdleMain.Name='Main'
profile.sequences.NinIdleMain.Values=T{ 'Tancho', 'AbysseaProcDagger', 'AbysseaProcSword', 'AbysseaProcGreatSword', 'AbysseaProcScythe', 'AbysseaProcPolearm', 'AbysseaProcKatana', 'AbysseaProcGreatKatana', 'AbysseaProcClub', 'AbysseaProcStaff' }
profile.sequences.NinIdleMain.Default='Tancho'
profile.sequences.NinIdleMain.Tancho='ac_var_IdleMain_Tancho'
profile.sequences.NinIdleMain.AbysseaProcDagger='ac_var_IdleMain_AbysseaProcDagger'
profile.sequences.NinIdleMain.AbysseaProcSword='ac_var_IdleMain_AbysseaProcSword'
profile.sequences.NinIdleMain.AbysseaProcGreatSword='ac_var_IdleMain_AbysseaProcGreatSword'
profile.sequences.NinIdleMain.AbysseaProcScythe='ac_var_IdleMain_AbysseaProcScythe'
profile.sequences.NinIdleMain.AbysseaProcPolearm='ac_var_IdleMain_AbysseaProcPolearm'
profile.sequences.NinIdleMain.AbysseaProcKatana='ac_var_IdleMain_AbysseaProcKatana'
profile.sequences.NinIdleMain.AbysseaProcGreatKatana='ac_var_IdleMain_AbysseaProcGreatKatana'
profile.sequences.NinIdleMain.AbysseaProcClub='ac_var_IdleMain_AbysseaProcClub'
profile.sequences.NinIdleMain.AbysseaProcStaff='ac_var_IdleMain_AbysseaProcStaff'

profile.sequences.NinStrategy=T{}
profile.sequences.NinStrategy.Name='Strategy'
profile.sequences.NinStrategy.Values=T{ 'MstrMelee', 'TH' }
profile.sequences.NinStrategy.Default='MstrMelee'
profile.sequences.NinStrategy.MstrMelee='ac_var_Strategy_MstrMelee'
profile.sequences.NinStrategy.TH='ac_var_Strategy_TH'

profile.sequences.RollOne=T{}
profile.sequences.RollOne.Name='Roll 1'
profile.sequences.RollOne.Values=T{ 'Exp', 'DblAtt', 'Mab', 'Macc', 'Crit', 'Att', 'Acc', 'Stp', 'Regain', 'Refresh', 'PetAcc', 'PetMacMab', 'PetAtt', 'PetRegain' }
profile.sequences.RollOne.Default='PetRegain'
profile.sequences.RollOne.Exp='cor_roll_1_corsairs' 
profile.sequences.RollOne.DblAtt='cor_roll_1_fighters' 
profile.sequences.RollOne.Mab='cor_roll_1_wizards' 
profile.sequences.RollOne.Macc='cor_roll_1_warlocks' 
profile.sequences.RollOne.Crit='cor_roll_1_rogues' 
profile.sequences.RollOne.Att='cor_roll_1_chaos' 
profile.sequences.RollOne.Acc='cor_roll_1_hunters' 
profile.sequences.RollOne.Stp='cor_roll_1_samurais' 
profile.sequences.RollOne.Regain='cor_roll_1_tacticians' 
profile.sequences.RollOne.Refresh='cor_roll_1_evokers' 
profile.sequences.RollOne.PetAcc='cor_roll_1_drachen' 
profile.sequences.RollOne.PetMacMab='cor_roll_1_puppet' 
profile.sequences.RollOne.PetAtt='cor_roll_1_beast' 
profile.sequences.RollOne.PetRegain='cor_roll_1_companion'

profile.sequences.RollTwo=T{}
profile.sequences.RollTwo.Name='Roll 2'
profile.sequences.RollTwo.Values=T{ 'Exp', 'DblAtt', 'Mab', 'Macc', 'Crit', 'Att', 'Acc', 'Stp', 'Regain', 'Refresh', 'PetAcc', 'PetMacMab', 'PetAtt', 'PetRegain' }
profile.sequences.RollTwo.Default='PetAcc'
profile.sequences.RollTwo.Exp='cor_roll_2_corsairs' 
profile.sequences.RollTwo.DblAtt='cor_roll_2_fighters' 
profile.sequences.RollTwo.Mab='cor_roll_2_wizards' 
profile.sequences.RollTwo.Macc='cor_roll_2_warlocks' 
profile.sequences.RollTwo.Crit='cor_roll_2_rogues' 
profile.sequences.RollTwo.Att='cor_roll_2_chaos' 
profile.sequences.RollTwo.Acc='cor_roll_2_hunters' 
profile.sequences.RollTwo.Stp='cor_roll_2_samurais' 
profile.sequences.RollTwo.Regain='cor_roll_2_tacticians' 
profile.sequences.RollTwo.Refresh='cor_roll_2_evokers' 
profile.sequences.RollTwo.PetAcc='cor_roll_2_drachen' 
profile.sequences.RollTwo.PetMacMab='cor_roll_2_puppet' 
profile.sequences.RollTwo.PetAtt='cor_roll_2_beast' 
profile.sequences.RollTwo.PetRegain='cor_roll_2_companion'

profile.sequences.SamWS=T{}
profile.sequences.SamWS.Name='Samurai WS'
profile.sequences.SamWS.Values=T{ 'Tachi_Fudo', 'Namas_Arrow' }
profile.sequences.SamWS.Default='Tachi_Fudo'
profile.sequences.SamWS.Tachi_Fudo='ws_setting_tachi_fudo'
profile.sequences.SamWS.Namas_Arrow='ws_setting_namas_arrow'

profile.sequences.SchSkillchain=T{}
profile.sequences.SchSkillchain.Name='Scholar Skillchain'
profile.sequences.SchSkillchain.Values=T{ 'Liq_F', 'Sci_S', 'Rev_W', 'Det_A', 'Ind_B', 'Inp_T', 'Trns_L', 'Com_D', 'Frag_AT', 'Fus_FL', 'Grav_DS', 'Dist_WB' }
profile.sequences.SchSkillchain.Default='Liq_F'
profile.sequences.SchSkillchain.Liq_F='sch_liq_f'
profile.sequences.SchSkillchain.Sci_S='sch_sci_s'
profile.sequences.SchSkillchain.Rev_W='sch_rev_w'
profile.sequences.SchSkillchain.Det_A='sch_det_a'
profile.sequences.SchSkillchain.Ind_B='sch_ind_b'
profile.sequences.SchSkillchain.Inp_T='sch_imp_t'
profile.sequences.SchSkillchain.Trns_L='sch_trns_l'
profile.sequences.SchSkillchain.Com_D='sch_com_d'
profile.sequences.SchSkillchain.Frag_AT='sch_frag_at'
profile.sequences.SchSkillchain.Fus_FL='sch_fus_fl'
profile.sequences.SchSkillchain.Grav_DS='sch_grav_ds'
profile.sequences.SchSkillchain.Dist_WB='sch_dist_wb'

profile.sequences.SongOne=T{}
profile.sequences.SongOne.Name='Song 1'
profile.sequences.SongOne.Values=T{ 'Ref1', 'Ref2', 'Ref3', 'Def5', 'Att5', 'AttDel1', 'AttDel2', 'Acc1', 'Acc2', 'Carol1', 'Carol2' }
profile.sequences.SongOne.Default='brdsong2attdel1'
profile.sequences.SongOne.Ref1='brdsong1ref1'
profile.sequences.SongOne.Ref2='brdsong1ref2'
profile.sequences.SongOne.Ref3='brdsong1ref3'
profile.sequences.SongOne.Def5='brdsong1def5'
profile.sequences.SongOne.Att5='brdsong1att5'
profile.sequences.SongOne.AttDel1='brdsong1attdel1'
profile.sequences.SongOne.AttDel2='brdsong1attdel2'
profile.sequences.SongOne.Acc1='brdsong1acc1'
profile.sequences.SongOne.Acc2='brdsong1acc2'
profile.sequences.SongOne.Carol1='brdsong1carol1'
profile.sequences.SongOne.Carol2='brdsong1carol2'

profile.sequences.SongTwo=T{}
profile.sequences.SongTwo.Name='Song 2'
profile.sequences.SongTwo.Values=T{ 'Ref1', 'Ref2', 'Ref3', 'Def5', 'Att5', 'AttDel1', 'AttDel2', 'Acc1', 'Acc2', 'Carol1', 'Carol2' }
profile.sequences.SongTwo.Default='brdsong2attdel2'
profile.sequences.SongTwo.Ref1='brdsong2ref1'
profile.sequences.SongTwo.Ref2='brdsong2ref2'
profile.sequences.SongTwo.Ref3='brdsong2ref3'
profile.sequences.SongTwo.Def5='brdsong2def5'
profile.sequences.SongTwo.Att5='brdsong2att5'
profile.sequences.SongTwo.AttDel1='brdsong2attdel1'
profile.sequences.SongTwo.AttDel2='brdsong2attdel2'
profile.sequences.SongTwo.Acc1='brdsong2acc1'
profile.sequences.SongTwo.Acc2='brdsong2acc2'
profile.sequences.SongTwo.Carol1='brdsong2carol1'
profile.sequences.SongTwo.Carol2='brdsong2carol2'

profile.sequences.SongThree=T{}
profile.sequences.SongThree.Name='Song 3'
profile.sequences.SongThree.Values=T{ 'Ref1', 'Ref2', 'Ref3', 'Def5', 'Att5', 'AttDel1', 'AttDel2', 'Acc1', 'Acc2', 'Carol1', 'Carol2' }
profile.sequences.SongThree.Default='brdsong3ref3'
profile.sequences.SongThree.Ref1='brdsong3ref1'
profile.sequences.SongThree.Ref2='brdsong3ref2'
profile.sequences.SongThree.Ref3='brdsong3ref3'
profile.sequences.SongThree.Def5='brdsong3def5'
profile.sequences.SongThree.Att5='brdsong3att5'
profile.sequences.SongThree.AttDel1='brdsong3attdel1'
profile.sequences.SongThree.AttDel2='brdsong3attdel2'
profile.sequences.SongThree.Acc1='brdsong3acc1'
profile.sequences.SongThree.Acc2='brdsong3acc2'
profile.sequences.SongThree.Carol1='brdsong3carol1'
profile.sequences.SongThree.Carol2='brdsong3carol2'

profile.sequences.SchWS=T{}
profile.sequences.SchWS.Name='Scholar WS'
profile.sequences.SchWS.Values=T{ 'Shattersoul', 'Myrkr', 'Cataclysm' }
profile.sequences.SchWS.Default='Shattersoul'
profile.sequences.SchWS.Shattersoul='ws_setting_shattersoul'
profile.sequences.SchWS.Myrkr='ws_setting_myrkr'
profile.sequences.SchWS.Cataclysm='ws_setting_cataclysm'

profile.sequences.ThrenodyElement=T{}
profile.sequences.ThrenodyElement.Name='Threnody Element'
profile.sequences.ThrenodyElement.Values=T{ 'Fire', 'Stone', 'Water', 'Wind', 'Ice', 'Thunder', 'Light', 'Dark' }
profile.sequences.ThrenodyElement.Default='Fire'
profile.sequences.ThrenodyElement.Fire='brd_threnody_element_fire'
profile.sequences.ThrenodyElement.Stone='brd_threnody_element_stone'
profile.sequences.ThrenodyElement.Water='brd_threnody_element_water'
profile.sequences.ThrenodyElement.Wind='brd_threnody_element_wind'
profile.sequences.ThrenodyElement.Ice='brd_threnody_element_ice'
profile.sequences.ThrenodyElement.Thunder='brd_threnody_element_thunder'
profile.sequences.ThrenodyElement.Light='brd_threnody_element_light'
profile.sequences.ThrenodyElement.Dark='brd_threnody_element_dark'

profile.sequences.WeaponStrategy=T{}
profile.sequences.WeaponStrategy.Name='Weapon Strategy'
profile.sequences.WeaponStrategy.Values=T{ 'NoSwap', 'Swap' }
profile.sequences.WeaponStrategy.Default='NoSwap'
profile.sequences.WeaponStrategy.NoSwap='ac_var_WeaponStrategy_NoSwap'
profile.sequences.WeaponStrategy.Swap='ac_var_WeaponStrategy_Swap'

return profile